<?php

declare(strict_types=1);

namespace Arcanum\Forge;

use Arcanum\Parchment\Reader;
use Arcanum\Parchment\Searcher;
use Arcanum\Parchment\Writer;
use Arcanum\Toolkit\Strings;

/**
 * Generates typed Model classes from SQL files.
 *
 * Scans a domain's Model/ directory for .sql files and produces a PHP
 * class that extends Forge\Model with a typed method for each file.
 * This is the engine behind the forge:models Rune command and dev-mode
 * auto-regeneration.
 */
final class ModelGenerator
{
    public function __construct(
        private readonly Reader $reader = new Reader(),
        private readonly Writer $writer = new Writer(),
    ) {
    }

    /**
     * Generate a model class for a single domain's Model/ directory.
     *
     * @param string $modelDir Absolute path to the Model/ directory containing .sql files.
     * @param string $namespace The fully qualified namespace for the generated class.
     * @return string The generated PHP source code.
     */
    public function generate(string $modelDir, string $namespace): string
    {
        $sqlFiles = $this->discoverSqlFiles($modelDir);

        $methods = [];
        foreach ($sqlFiles as $file) {
            $methods[] = $this->buildMethod($file);
        }

        return $this->render($namespace, $methods);
    }

    /**
     * Generate and write the model class file.
     *
     * @return bool True if written, false if no SQL files found.
     */
    public function generateAndWrite(string $modelDir, string $namespace, string $outputPath): bool
    {
        $sqlFiles = $this->discoverSqlFiles($modelDir);

        if ($sqlFiles === []) {
            return false;
        }

        $source = $this->generate($modelDir, $namespace);
        $this->writer->write($outputPath, $source);

        return true;
    }

    /**
     * Check if any SQL file in the directory is newer than the generated class.
     */
    public function isStale(string $modelDir, string $classFile): bool
    {
        if (!is_file($classFile)) {
            return true;
        }

        $classTime = filemtime($classFile);
        if ($classTime === false) {
            return true;
        }

        $sqlFiles = $this->discoverSqlFiles($modelDir);

        foreach ($sqlFiles as $file) {
            $sqlTime = filemtime($file);
            if ($sqlTime !== false && $sqlTime > $classTime) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return list<string> Sorted absolute paths to .sql files.
     */
    private function discoverSqlFiles(string $modelDir): array
    {
        if (!is_dir($modelDir)) {
            return [];
        }

        $files = [];
        foreach (Searcher::findAll('*.sql', $modelDir) as $file) {
            $files[] = $file->getRealPath();
        }
        sort($files);

        return $files;
    }

    private function buildMethod(string $sqlFile): string
    {
        $filename = basename($sqlFile, '.sql');
        $methodName = lcfirst($filename);
        $sql = $this->reader->read($sqlFile);

        $paramAnnotations = Sql::parseParams($sql);
        $bindings = Sql::extractBindings($sql);

        $params = $this->buildParams($bindings, $paramAnnotations);

        $arrayEntries = [];
        foreach ($bindings as $binding) {
            $phpName = Strings::camel($binding);
            $arrayEntries[] = sprintf("            '%s' => \$%s,", $binding, $phpName);
        }

        $signature = $params !== [] ? implode(', ', $params) : '';
        $body = $arrayEntries !== []
            ? sprintf(
                "return \$this->__call('%s', [[\n%s\n        ]]);",
                $methodName,
                implode("\n", $arrayEntries),
            )
            : sprintf("return \$this->__call('%s', []);", $methodName);

        return sprintf(
            "    public function %s(%s): Result\n    {\n        %s\n    }",
            $methodName,
            $signature,
            $body,
        );
    }

    /**
     * @param list<string> $bindings
     * @param array<string, string> $paramAnnotations
     * @return list<string>
     */
    private function buildParams(array $bindings, array $paramAnnotations): array
    {
        $params = [];

        foreach ($bindings as $binding) {
            $type = $paramAnnotations[$binding] ?? 'string';
            $phpName = Strings::camel($binding);
            $params[] = sprintf('%s $%s', $type, $phpName);
        }

        return $params;
    }

    /**
     * @param list<string> $methods
     */
    private function render(string $namespace, array $methods): string
    {
        $methodBlock = implode("\n\n", $methods);

        $lines = [
            '<?php',
            '',
            '// This file is auto-generated by forge:models. Do not edit.',
            '',
            'declare(strict_types=1);',
            '',
            sprintf('namespace %s;', Strings::classNamespace($namespace)),
            '',
            'use Arcanum\Forge\Model as BaseModel;',
            'use Arcanum\Forge\Result;',
            '',
            sprintf('final class %s extends BaseModel', Strings::classBaseName($namespace)),
            '{',
            $methodBlock,
            '}',
            '',
        ];

        return implode("\n", $lines);
    }
}
